---
- name: instalando dependencias do docker
  hosts: docker

  tasks:
    - name: instalando o python-pip
      apt:
        name: python-pip
        state: present

    - name: instalando a dependencia pro docker funfar com ansible
      pip:
        name: docker-py

    - name: instalando o docker
      apt:
        name: docker-ce
        state: present
